name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # 确保在任何 Git 操作前先配置身份
      - name: Configure Git
        run: |
          git config --global user.name "一闪一闪亮晶晶"
          git config --global user.email "resetsix223@gmail.com"
          
      - name: Add remote upstream
        run: git remote add upstream https://github.com/bytedance/flowgram.ai
        
      - name: Fetch upstream
        run: git fetch upstream
        
      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
